# Generated by Django 3.1.3 on 2021-04-08 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0003_auto_20210408_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='resource',
        ),
        migrations.AddField(
            model_name='workitem',
            name='resources',
            field=models.ManyToManyField(related_name='resouce', to=settings.AUTH_USER_MODEL),
        ),
    ]
