# Generated by Django 3.1.3 on 2021-04-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20210408_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='allocatedHour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
