# Generated by Django 3.1.3 on 2021-04-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0002_workitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('workDate', models.DateField()),
                ('remark', models.TextField()),
                ('workItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.workitem')),
            ],
        ),
    ]
