# Generated by Django 3.1.3 on 2021-04-08 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0002_timesheet_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='resource',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='loggedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='resources',
            field=models.ManyToManyField(related_name='resource', to=settings.AUTH_USER_MODEL),
        ),
    ]
