# Generated by Django 3.1.3 on 2021-04-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_auto_20210408_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='resources',
        ),
    ]
