# Generated by Django 3.1.3 on 2021-04-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_remove_timesheet_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
